version: '3.8'

services:
  db:
    image: postgres:15
    container_name: livelib_postgres
    environment:
      POSTGRES_DB: livelib_db
      POSTGRES_USER: livelib_user
      POSTGRES_PASSWORD: livelib_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U livelib_user -d livelib_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: src/main/java/com/example/livelib
    container_name: livelib_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/livelib_db
      SPRING_DATASOURCE_USERNAME: livelib_user
      SPRING_DATASOURCE_PASSWORD: livelib_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_DEFAULT_PASSWORD: defaultpassword123 # Установите более сложный пароль
    # Если вы хотите, чтобы приложение запускалось только после готовности БД
    # command: >
    #   sh -c "sleep 30 && java -jar app.jar"

volumes:
  postgres_data: